// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailcustom.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the EmailCustom module
	public static void __Example_SendEmail(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			Core.execute(context, "EmailCustom.__Example_SendEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createAndQueuedEmail(IContext context, emailcustom.proxies.EmailInfo _emailInfo, emailtemplate.proxies.EmailTemplate _emailTemplate, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			params.put("EmailAddress", _emailAddress);
			Core.execute(context, "EmailCustom.CreateAndQueuedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createAndSendEmail(IContext context, emailcustom.proxies.EmailInfo _emailInfo, emailtemplate.proxies.EmailTemplate _emailTemplate, java.lang.String _emailAddress)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			params.put("EmailAddress", _emailAddress);
			Core.execute(context, "EmailCustom.CreateAndSendEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void retrieveTemplateAndQueueEmail(IContext context, java.lang.String _emailAddress, java.lang.String _templateName, emailcustom.proxies.EmailInfo _emailInfo)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			params.put("TemplateName", _templateName);
			params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
			Core.execute(context, "EmailCustom.RetrieveTemplateAndQueueEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void retrieveTemplateAndSendEmail(IContext context, java.lang.String _emailAddress, java.lang.String _templateName, emailcustom.proxies.EmailInfo _emailInfo)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("EmailAddress", _emailAddress);
			params.put("TemplateName", _templateName);
			params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
			Core.execute(context, "EmailCustom.RetrieveTemplateAndSendEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}