// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailcustom.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the EmailCustom module
	public static void __Example_SendEmail(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("EmailCustom.__Example_SendEmail").withParams(params).execute(context);
	}
	public static void createAndQueuedEmail(IContext context, emailcustom.proxies.EmailInfo _emailInfo, emailtemplate.proxies.EmailTemplate _emailTemplate, java.lang.String _emailAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailAddress", _emailAddress);
		Core.microflowCall("EmailCustom.CreateAndQueuedEmail").withParams(params).execute(context);
	}
	public static void createAndSendEmail(IContext context, emailcustom.proxies.EmailInfo _emailInfo, emailtemplate.proxies.EmailTemplate _emailTemplate, java.lang.String _emailAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailAddress", _emailAddress);
		Core.microflowCall("EmailCustom.CreateAndSendEmail").withParams(params).execute(context);
	}
	public static void retrieveTemplateAndQueueEmail(IContext context, java.lang.String _emailAddress, java.lang.String _templateName, emailcustom.proxies.EmailInfo _emailInfo)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailAddress", _emailAddress);
		params.put("TemplateName", _templateName);
		params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
		Core.microflowCall("EmailCustom.RetrieveTemplateAndQueueEmail").withParams(params).execute(context);
	}
	public static void retrieveTemplateAndSendEmail(IContext context, java.lang.String _emailAddress, java.lang.String _templateName, emailcustom.proxies.EmailInfo _emailInfo)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailAddress", _emailAddress);
		params.put("TemplateName", _templateName);
		params.put("EmailInfo", _emailInfo == null ? null : _emailInfo.getMendixObject());
		Core.microflowCall("EmailCustom.RetrieveTemplateAndSendEmail").withParams(params).execute(context);
	}
}