// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailcustom.proxies;

public class EmailInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmailCustom.EmailInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Info("Info"),
		Attribute("Attribute"),
		Attribute_2("Attribute_2"),
		Attribute_3("Attribute_3");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmailCustom.EmailInfo"));
	}

	protected EmailInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailInfoMendixObject)
	{
		if (emailInfoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmailCustom.EmailInfo", emailInfoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmailCustom.EmailInfo");

		this.emailInfoMendixObject = emailInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emailcustom.proxies.EmailInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emailcustom.proxies.EmailInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emailcustom.proxies.EmailInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emailcustom.proxies.EmailInfo(context, mendixObject);
	}

	public static emailcustom.proxies.EmailInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emailcustom.proxies.EmailInfo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Info
	 */
	public final java.lang.String getInfo()
	{
		return getInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of Info
	 */
	public final java.lang.String getInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Info.toString());
	}

	/**
	 * Set value of Info
	 * @param info
	 */
	public final void setInfo(java.lang.String info)
	{
		setInfo(getContext(), info);
	}

	/**
	 * Set value of Info
	 * @param context
	 * @param info
	 */
	public final void setInfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String info)
	{
		getMendixObject().setValue(context, MemberNames.Info.toString(), info);
	}

	/**
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute.toString());
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(java.lang.String attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute)
	{
		getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute);
	}

	/**
	 * @return value of Attribute_2
	 */
	public final java.lang.String getAttribute_2()
	{
		return getAttribute_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_2
	 */
	public final java.lang.String getAttribute_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute_2.toString());
	}

	/**
	 * Set value of Attribute_2
	 * @param attribute_2
	 */
	public final void setAttribute_2(java.lang.String attribute_2)
	{
		setAttribute_2(getContext(), attribute_2);
	}

	/**
	 * Set value of Attribute_2
	 * @param context
	 * @param attribute_2
	 */
	public final void setAttribute_2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute_2)
	{
		getMendixObject().setValue(context, MemberNames.Attribute_2.toString(), attribute_2);
	}

	/**
	 * @return value of Attribute_3
	 */
	public final java.lang.String getAttribute_3()
	{
		return getAttribute_3(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute_3
	 */
	public final java.lang.String getAttribute_3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute_3.toString());
	}

	/**
	 * Set value of Attribute_3
	 * @param attribute_3
	 */
	public final void setAttribute_3(java.lang.String attribute_3)
	{
		setAttribute_3(getContext(), attribute_3);
	}

	/**
	 * Set value of Attribute_3
	 * @param context
	 * @param attribute_3
	 */
	public final void setAttribute_3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute_3)
	{
		getMendixObject().setValue(context, MemberNames.Attribute_3.toString(), attribute_3);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailcustom.proxies.EmailInfo that = (emailcustom.proxies.EmailInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmailCustom.EmailInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
